title: Pedro Bagatin
theme: jekyll-theme-architect
show_downloads: true
github:
  about_url: /index.html
  contact_url: /contact.html
  linkedin_url: https://www.linkedin.com/in/pedro-bermudez-827990b7/
